name: CI/CD

on: [push, pull_request]

jobs:
  tests:
    name: Test Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build Image
        uses: docker/build-push-action@v1.0.0
        with:
          repository: iksaku/openstack-swift-container
          tags: latest
          push: false

      - name: "[Test] Print Swift Version"
        env:
          INPUT_AUTH_CHECK: false
        run: docker run --rm -e INPUT_AUTH_CHECK iksaku/openstack-swift-container --version

      - name: "[Test] Lists files"
        env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
        run: docker run --rm -e OS_AUTH_URL -e OS_PASSWORD -e OS_PROJECT_NAME -e OS_REGION_NAME -e OS_USERNAME -e OS_USER_DOMAIN_NAME iksaku/openstack-swift-container list openstack-swift-action

  push:
    name: Push to Docker Registry
    runs-on: ubuntu-latest
    if: github.repository == 'iksaku/openstack-swift-container'
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build and Publish to Docker Registry
        uses: docker/build-push-action@v1.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: iksaku/openstack-swift-container
          tags: ussuri-dev,3-dev,3.9-dev,3.9.0-dev
